#cloud-config
repo_update: true
repo_upgrade: all

write_files:
  - path: /var/docker/docker-compose.yml
    permissions: 0644
    owner: ec2-user:ec2-user
    content: |
      version: "3.7"
      services:
        exporter:
          image: prom/node-exporter
          container_name: node-exporter
          ports:
            - "9100:9100"
          network_mode: "host"
          restart: always
        cadvisor:
          image: google/cadvisor:latest
          container_name: cadvisor
          volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker:/var/lib/docker:ro
          ports:
            - "8080:8080"
          privileged: true
          networks:
            default:
              aliases:
                - cadvisor
          restart: always
        tenant1:
          image: nginx:latest
          container_name: tenant1
          ports:
            - "80:80"
        tenant2:
          image: nginx:latest
          container_name: tenant2
          ports:
            - "81:80"

runcmd:
  - [sh, -c, "amazon-linux-extras install -y docker"]
  - sudo systemctl start docker
  - sudo systemctl enable docker
  - [sh, -c, "usermod -a -G docker ec2-user"]
  - [sh, -c, "curl -L \"https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose"]
  - [sh, -c, "chmod +x /usr/local/bin/docker-compose"]
  - [sh, -c, "docker-compose -f /var/docker/docker-compose.yml up -d"]
