#cloud-config
repo_update: true
repo_upgrade: all

runcmd:
  - [sh, -c, "amazon-linux-extras install -y docker"]
  - sudo systemctl start docker
  - sudo systemctl enable docker
  - [sh, -c, "usermod -a -G docker ec2-user"]
  - [sh, -c, "docker run -d -p 9100:9100 --net='host' --name node-exporter prom/node-exporter"]
