version: "3.7"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config:/prometheus-config
    command: "--config.file=/prometheus-config/prometheus.yml"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/config:/grafana-config
