---
global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "docker"
    static_configs:
      - targets:
          - "52.194.232.119:8080"
          - "52.192.205.188:8080"
        labels:
          group: "docker"
  - job_name: "docker_hosts"
    static_configs:
      - targets:
          - "52.194.232.119:9100"
          - "52.192.205.188:9100"
        labels:
          group: "docker_host"
  - job_name: "ec2_hosts"
    # EC2 Service Discovery Config
    ec2_sd_configs:
      - region: "ap-northeast-1"
        access_key: ""
        secret_key: ""
        port: 9100
        refresh_interval: 60s
        filters:
          - name: "tag:ENV"
            values: ["prd"]