---
global:
  scrape_interval: 1m

scrape_configs:
  # - job_name: "static_hosts"
  #   static_configs:
  #     - targets:
  #         - "18.179.19.76:9100"
  #         - "13.231.249.42:9100"
  - job_name: "ec2_hosts"
    # EC2 Service Discovery Config
    ec2_sd_configs:
      - region: "ap-northeast-1"
        access_key: ""
        secret_key: ""
        port: 9100
        refresh_interval: 60s
        filters:
          - name: "tag:ENV"
            values: ["prd"]