---
global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "docker"
    static_configs:
      - targets:
          - "13.113.40.173:8080"
          - "3.112.17.34:8080"
        labels:
          group: "docker"
          container_group: "docker"
  - job_name: "docker_hosts"
    static_configs:
      - targets:
          - "13.113.40.173:9100"
          - "3.112.17.34:9100"
        labels:
          group: "docker_host"
          container_group: "docker_host"
  - job_name: "ec2_hosts"
    # EC2 Service Discovery Config
    ec2_sd_configs:
      - region: "ap-northeast-1"
        access_key: ""
        secret_key: ""
        port: 9100
        refresh_interval: 60s
        filters:
          - name: "tag:ENV"
            values: ["prd"]